
#General settings
[General]
	#Default Howler Alarm Range
	#Range: > 0
	howlerAlarmRange = 64
	#Max Possible Howler Alarm Range
	#Range: > 0
	maxAlarmRange = 128
	#Allowed Alarms
	allowedAlarms = "default,sci-fi,siren"
	#Default Panel Refresh Period
	#Range: > 1
	infoPanelRefreshPeriod = 20
	#Default Range Trigger Refresh Period
	#Range: > 1
	rangeTriggerRefreshPeriod = 20
	#Default Thermal Monitor Refresh Period
	#Range: > 1
	thermalMonitorRefreshPeriod = 20
	#Load Custom Sounds
	useCustomSounds = false
	#Alarm Pause in Ticks
	#Range: 10 ~ 2000
	alarmPause = 60
	#Disable Range Check
	disableRangeCheck = false
	#Web Socket Enabled
	wsEnabled = false
	#Web Socket Host
	wsHost = ""
	#Web Socket Port
	#Range: 1 ~ 99999
	wsPort = 1
	#Web Socket Token
	wsToken = "78c2b80a-1203-43fd-a9af-75cec29f5acf"
	#Web Socket Refresh Rate
	#Range: 10 ~ 20000
	wsRefreshRate = 100
	#Web Socket Server ID
	wsServerID = "790f2c19-162f-405d-897f-1abe284d4732"

